- type: job
  id: PirateCaptain
  name: job-name-pirate-captain
  description: job-description-pirate-captain
  playTimeTracker: JobPirateCaptain
  requirements:
    - !type:OverallPlaytimeRequirement # mono start
      time: 144000 # 40 hours
    - !type:RoleTimeRequirement
      role: JobPirateFirstMate
      time: 18000 # 5 hours - mono
  whitelisted: true
  startingGear: PirateCaptainNFGear
  alwaysUseSpawner: true
  hideConsoleVisibility: true
  canBeAntag: true
  icon: "JobIconPirateCaptain"
  supervisors: job-supervisors-nobody
  weight: 50
  displayWeight: 50
  setPreference: true
  guides: [ BasicLore, PhaethonDynasty ] # Mono
  access:
  - Pirate
  - GrandVizier
  - PDVCommand
  - Mercenary
  accessGroups:
  - GeneralAccess
  special:
  - !type:AddComponentSpecial
    components:
    - type: NpcFactionMember
      factions:
      - PirateNF
  - !type:AddImplantSpecial
    implants: [ FreelanceTrackingImplant ]
  - !type:AddLanguageSpecial # Monolith - Languages
    languagesSpoken:
    - Freespeak
    languagesUnderstood:
    - Freespeak
  - !type:GiveItemOnHolidaySpecial # Even pirates get a piece of cake.
    holiday: FrontierBirthday
    prototype: FrontierBirthdayGift

- type: startingGear
  id: PirateCaptainNFGear
  equipment:
    ears: ClothingHeadsetAltVanguardCommand
    #belt: ClothingBeltUtility # mono
    pocket1: BasePirateUplinkRadioPirateCaptain
    pocket2: EnergySword
  storage:
    back:
    - RadioHandheldNF # mono
    - ShipVoucherSaintie
