# SPDX-FileCopyrightText: 2024 Dvir
# SPDX-FileCopyrightText: 2024 Salvantrix
# SPDX-FileCopyrightText: 2024 Whatstone
# SPDX-FileCopyrightText: 2025 Arcticular
# SPDX-FileCopyrightText: 2025 Blu
# SPDX-FileCopyrightText: 2025 NazrinNya
# SPDX-FileCopyrightText: 2025 dustylens
# SPDX-FileCopyrightText: 2025 starch
# SPDX-FileCopyrightText: 2025 thoughtlessuser
#
# SPDX-License-Identifier: MPL-2.0

- type: department
  id: Frontier
  name: department-Frontier
  description: department-NF-description
  color: "#334E6D"
  weight: 50 # accounted for in jobs
  roles:
  - StationRepresentative
  - StationTrafficController
  - CCServiceWorker # nyano
  - NFJanitor
  - MailCarrier # nyano
  - SecurityGuard

- type: department
  id: Antag
  name: department-Antag
  description: department-NFAntag-description
  color: "#DE3A3A"
  weight: 115 # Mono
  roles:
  - PirateCaptain
  - PirateFirstMate
  - PDVDenasvar # Mono
  - Pirate
  - PDVInfiltrator # Mono
  - PdvBorg # Mono
  - Prisoner #nyano
