- type: job
  id: Bailiff
  name: job-name-bailiff
  description: job-description-bailiff
  playTimeTracker: JobWarden
  requirements: # mono - lowers all of these tbh
    - !type:OverallPlaytimeRequirement
      time: 72000 # 20 hours
    - !type:DepartmentTimeRequirement
      department: Security
      time: 36000 # 10 hours
    - !type:RoleTimeRequirement
      role: JobSeniorOfficer
      time: 10800 # 3 hours
  startingGear: BailiffGear
  icon: JobIconBailiff
  supervisors: job-supervisors-sheriff
  weight: 150
  displayWeight: 60
  canBeAntag: false
  guides: [ BasicLore, TransSolarFederation ] # Mono
  access:
  - Armory
  - Sergeant
  - Bailiff
  - Medical
  - Chemistry
  - TsfmcEngineering # Mono
  accessGroups:
  - GeneralNfsdAccess
  special:
  - !type:AddComponentSpecial
    components:
    - type: NpcFactionMember
      factions:
      - TSFMC
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, TrackingImplant ]
  - !type:AddLanguageSpecial
    languagesSpoken:
    - SolCommon
    languagesUnderstood:
    - SolCommon
  - !type:GiveItemOnHolidaySpecial
    holiday: FrontierBirthday
    prototype: FrontierBirthdayGift

- type: startingGear
  id: BailiffGear
  equipment:
    pocket1: WeaponPistolMk58 #WeaponPistolMk58Nonlethal
  storage:
    back:
    - Magazine45_ACPPistolFMJ
    - BaseSecurityUplinkRadioOfficer
#    - ShipVoucherNfsdBailiff # Mono
    - RubberStampBailiff
    - RadioHandheldNF # Mono
