# SPDX-FileCopyrightText: 2023 Checkraze
# SPDX-FileCopyrightText: 2023 Dvir
# SPDX-FileCopyrightText: 2025 thoughtlessuser
#
# SPDX-License-Identifier: MPL-2.0

- type: playTimeTracker
  id: JobMailCarrier

- type: playTimeTracker
  id: JobPrisoner

- type: playTimeTracker
  id: JobCCServiceWorker

- type: playTimeTracker
  id: JobPrisonGuard

